### ISSUE TITLE
cuSolver internal error

### ISSUE THREAD

**Issue by lihao881230** [dattalab/keypoint-moseq#107] opened 2023-10-30 23:45 UTC
Hi all,

I am also running into the cuSolver internal error on Windows 11 (CUBA 11.1 and cuDNN 8.2), which is pretty much described in issues #69 and #103 . I have tried both conda install and pip install and they gave me the same error. I was wondering if anyone has found a solution to this. 

![image](https://github.com/dattalab/keypoint-moseq/assets/33735170/cdb6ae20-9903-469e-935d-c684f21583b3)

![image](https://github.com/dattalab/keypoint-moseq/assets/33735170/bce94316-f913-4a27-88d5-ea752a57dce6)

**Comment by calebweinreb** [comment] 2023-10-31 15:02
I think the problem is that JAX isn't currently supported on Windows 11. Looking at issue https://github.com/dattalab/keypoint-moseq/issues/103, it seems like the best workaround for now is to use WSL2.

**Comment by KonradDanielewski** [comment] 2023-11-14 13:05
I was testing some solutions to this issue and seems that it's just related to the `cudnn` and `cudatoolkit` installation in the env. I will have a fully tested solution later today and will write the specific versions and commands here - I just wanna test in on another  computer also to see if it's not a fluke and maybe I just did something more than I think - I'm still running into OOMs (I think, `jax` seems to fail silently when it OOMs and just leads to kernel death)

**Comment by calebweinreb** [comment] 2023-11-14 15:38
Thanks for working on this Konrad!

**Comment by KonradDanielewski** [comment] 2023-11-14 16:09
Should be fixed with #110

**Comment by calebweinreb** [comment] 2023-11-22 22:35
https://github.com/dattalab/keypoint-moseq/pull/110 is now merged into main. Thanks @KonradDanielewski !

**Closed by calebweinreb** 2023-11-22 22:35 UTC
